end_tag – FoXy
end_tag Function
9 statements
Source File
private pure function end_tag(self, is_indented) result(tag_)
Return </tag_name> end tag.
Type Bound
xml_tag
Arguments
Type Intent Optional Attributes Name
class(xml_tag), intent(in) :: self
XML tag.
logical, intent(in), optional :: is_indented
Activate content indentation.
Return Value character(len=:), allocatable
The end tag string.
Called by
Source Code
   pure function end_tag(self, is_indented) result(tag_)
   !< Return `</tag_name>` end tag.
   class(xml_tag), intent(in)           :: self        !< XML tag.
   logical,        intent(in), optional :: is_indented !< Activate content indentation.
   character(len=:), allocatable        :: tag_        !< The end tag string.
   tag_ = '</'//self%tag_name//'>'
   if (present(is_indented)) then
      if (is_indented) tag_ = repeat(' ', self%indent)//tag_
   endif
   endfunction end_tag
Call graph
stringify calls end_tag, stringify, stringify_recursive
create_tag_nested calls stringify
stringify_recursive calls stringify, stringify_recursive
write_tag calls stringify
foxy_test_add_attributes calls stringify
foxy_test_create_tag calls stringify
foxy_test_delete_attributes calls stringify
foxy_test_delete_content calls stringify
foxy_test_indent_tag calls stringify
xml_tag calls create_tag_nested
foxy_test_add_tag calls stringify
foxy_test_delete_tag calls stringify
foxy_test_parse_file_simple calls stringify
foxy_test_parse_string_nested_tags calls stringify
foxy_test_parse_string_simple calls stringify
foxy_test_write_tag calls stringify