bcton – FoXy
bcton Interface
Source File
public interface bcton
Convert bit-string to number (real and integer, bit-string to number type casting).
Calls
Module Procedures
private elemental function bctor_R8P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
real(kind=R8P), intent(in) :: knd
Number kind.
Return Value real(kind=R8P)
Number returned.
Description
Convert bit-string to real.
private elemental function bctor_R4P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
real(kind=R4P), intent(in) :: knd
Number kind.
Return Value real(kind=R4P)
Number returned.
Description
Convert bit-string to real.
private elemental function bctoi_I8P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
integer(kind=I8P), intent(in) :: knd
Number kind.
Return Value integer(kind=I8P)
Number returned.
Description
Convert bit-string to integer.
private elemental function bctoi_I4P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
integer(kind=I4P), intent(in) :: knd
Number kind.
Return Value integer(kind=I4P)
Number returned.
Description
Convert bit-string to integer.
private elemental function bctoi_I2P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
integer(kind=I2P), intent(in) :: knd
Number kind.
Return Value integer(kind=I2P)
Number returned.
Description
Convert bit-string to integer.
private elemental function bctoi_I1P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
integer(kind=I1P), intent(in) :: knd
Number kind.
Return Value integer(kind=I1P)
Number returned.
Description
Convert bit-string to integer.
Call graph
bcton calls bctoi_i2p, bctor_r4p, bctoi_i8p, bctoi_i1p, bctoi_i4p, bctor_r8p
bctoi_i2p calls str
bctor_r4p calls str
bctoi_i8p calls str
bctoi_i1p calls str
bctoi_i4p calls str
bctor_r8p calls str
str calls strf_i8p, str_a_i2p, str_r8p, str_a_r4p, strf_i1p, str_r4p, str_i2p, str_i8p, str_i4p, str_a_i4p, strf_i2p, strf_r8p, str_a_r8p, str_a_i8p, str_i1p, str_a_i1p, strf_r4p, str_bol, strf_i4p
str_a_i2p calls str_i2p
str_r8p calls compact_real_string
str_a_r4p calls str_r4p
str_r4p calls compact_real_string
str_a_i4p calls str_i4p
str_a_r8p calls str_r8p
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p