xml_tag – FoXy
xml_tag Interface
3 statements
Source File
public interface xml_tag
Overload xml_tag with creator procedures.
Calls
Module Procedures
private pure function create_tag_flat(name, attribute, attributes, attributes_stream, sanitize_attributes_value, pos, content, indent, is_content_indented, is_self_closing, id, level, parent_id, attributes_stream_alloc, content_alloc) result(tag)
Return an instance of xml tag.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Tag name.
character(len=*), intent(in), optional :: attribute(1:)
Attribute name/value pair [1:2].
character(len=*), intent(in), optional :: attributes(1:,1:)
Attributes list of name/value pairs [1:2,1:].
character(len=*), intent(in), optional :: attributes_stream
Attributes list as single stream.
logical, intent(in), optional :: sanitize_attributes_value
Sanitize attributes value.
integer(kind=I4P), intent(in), optional :: pos(1:)
Characters position (in source) indexes.
character(len=*), intent(in), optional :: content
Tag value.
integer(kind=I4P), intent(in), optional :: indent
Number of indent-white-spaces.
logical, intent(in), optional :: is_content_indented
Activate content indentation.
logical, intent(in), optional :: is_self_closing
The tag is self closing.
integer(kind=I4P), intent(in), optional :: id
Uniq ID.
integer(kind=I4P), intent(in), optional :: level
Tag hierarchy level.
integer(kind=I4P), intent(in), optional :: parent_id
Parent uniq ID.
character(len=:), intent(in), optional, allocatable :: attributes_stream_alloc
Attributes list stream, allocatable input.
character(len=:), intent(in), optional, allocatable :: content_alloc
Tag value, allocatable input.
Return Value type(xml_tag)
XML tag.
private pure function create_tag_nested(name, content, attribute, attributes, attributes_stream, sanitize_attributes_value, pos, indent, is_content_indented, id, level, parent_id, attributes_stream_alloc, content_alloc) result(tag)
Return an instance of xml tag with value being a nested tag.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Tag name.
type(xml_tag), intent(in) :: content
Tag value as nested tag..
character(len=*), intent(in), optional :: attribute(1:)
Attribute name/value pair [1:2].
character(len=*), intent(in), optional :: attributes(1:,1:)
Attributes list of name/value pairs [1:2,1:].
character(len=*), intent(in), optional :: attributes_stream
Attributes list as single stream.
logical, intent(in), optional :: sanitize_attributes_value
Sanitize attributes value.
integer(kind=I4P), intent(in), optional :: pos(1:)
Characters position (in source) indexes.
integer(kind=I4P), intent(in), optional :: indent
Number of indent-white-spaces.
logical, intent(in), optional :: is_content_indented
Activate value indentation.
integer(kind=I4P), intent(in), optional :: id
Uniq ID.
integer(kind=I4P), intent(in), optional :: level
Tag hierarchy level.
integer(kind=I4P), intent(in), optional :: parent_id
Parent uniq ID.
character(len=:), intent(in), optional, allocatable :: attributes_stream_alloc
Attributes list stream, allocatable input.
character(len=:), intent(in), optional, allocatable :: content_alloc
Tag value, allocatable input.
Return Value type(xml_tag)
XML tag.
Call graph
xml_tag calls create_tag_flat, create_tag_nested
create_tag_flat calls set
create_tag_nested calls set, stringify
set calls add_multiple_attributes, add_single_attribute, add_stream_attributes
stringify calls chars, is_allocated, end_tag, self_closing_tag, start_tag
add_multiple_attributes calls add_single_attribute
add_single_attribute calls alloc_attributes
add_stream_attributes calls add_single_attribute, fill, partition, slice